"""user_game_history

Revision ID: 1152b6c137ae
Revises: 5649f99dbfa3
Create Date: 2024-05-15 17:58:26.368917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1152b6c137ae'
down_revision = '5649f99dbfa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_quiz_questions_users', type_='foreignkey')

    # Create the user_game_history table
    op.create_table(
        'user_game_history',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('game_name', sa.String(length=100), nullable=False),
        sa.Column('correct_answers', sa.Integer(), nullable=False),
        sa.Column('attempts', sa.Integer(), nullable=False),
        sa.Column('completion_time', sa.REAL(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id']),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_quiz_questions_users', 'user', ['user_id'], ['id'])

    # Drop the user_game_history table
    op.drop_table('user_game_history')
    # ### end Alembic commands ###
